[package]
name = "p2pro-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[workspace]
members = [
    "p2pro-hw",
    "p2pro-cli",
]

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.91"
license = "MIT"
authors = [ "Michael Büsch <m@bues.ch>" ]
homepage = "https://bues.ch/"
repository = "https://github.com/mbuesch/p2pro-rs"
readme = "README.md"
categories = [ "graphics", "hardware-support", "science" ]
keywords = [ "infiray", "p2pro", "thermal", "camera" ]

[workspace.dependencies]
android_logger = "0.15"
anyhow = "1"
autocfg = "1"
base64 = "0.23"
chrono = "0.4"
clap = "4"
curveipo = { version = "1", features = [ "fastfloat" ] }
dioxus = { version = "0.7", default-features = false }
image = { version = "0.25", default-features = false }
jni = "0.22"
libc = "0.2"
log = "0.4"
movavg = "3"
nusb = { version = "0.2", features = [ "tokio" ] }
oxideav-avi = "0.0.10"
oxideav-core = "0.1"
oxideav-huffyuv = "0.0.3"
p2pro-hw = { path = "p2pro-hw", default-features = false }
rfd = { version = "0.17", default-features = false }
rusb = { version = "0.9", features = [ "vendored" ] }
tokio = { version = "1", default-features = false, features = [ "sync", "fs", "time", "rt-multi-thread" ] }
v4l = "0.14"

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
curveipo.workspace = true
image.workspace = true
libc.workspace = true
log.workspace = true
movavg.workspace = true
nusb = { workspace = true, optional = true }
oxideav-avi.workspace = true
oxideav-core.workspace = true
oxideav-huffyuv.workspace = true
p2pro-hw = { workspace = true, features = [ "tokio" ] }
rusb = { workspace = true, optional = true }
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
clap = { workspace = true, features = [ "derive" ] }
dioxus = { workspace = true, features = [ "desktop", "minimal", "document" ] }
rfd = { workspace = true, features = [ "xdg-portal" ] }
v4l.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
dioxus = { workspace = true, features = [ "mobile", "minimal", "document" ] }
jni.workspace = true

[features]
default = [ "nusb", ]
rusb = [ "dep:rusb", "p2pro-hw/rusb" ]
nusb = [ "dep:nusb", "p2pro-hw/nusb" ]

[build-dependencies]
autocfg.workspace = true
image = { workspace = true, features = [ "png" ] }

[profile.dev]
debug = "limited"
panic = "abort"

[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"
codegen-units = 1
